services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      DISK_SIZE: "128G"
      RAM_SIZE: "12G"
      CPU_CORES: "4"
      DISK_TYPE: "ide"
      VERSION: "tiny11"
      ARGUMENTS: "-drive file=/driver.iso,media=cdrom"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /mnt:/storage
      - /isos/driver.iso:/driver.iso
    stop_grace_period: 2m
